### ISSUE TITLE
Postgres Error caused by RenameConversationLocked migration

### ISSUE THREAD

**Issue by cashby** [columbusrb/conclave#104]
Unable to complete db:migrate (Postgres on Heroku) after this migration was added. It chokes on this migration and can't get past it.

Notice schema.rb line 65 still has a reference to :locked even though the column name and index names were changed.

``` ruby
  add_index "conversations", ["closed"], :name => "index_conversations_on_locked"
```
- I ran a new rename_index migration attempting to force a change to the :name => part, but it didn't work.
- I ran a new remove_index migration and then a new add_index migration, but that didn't work.

It doesn't help to create new migrations that run after RenameConversationLocked because the migration stops there and doesn't run anything after it.

My local repository is completely up-to-date with my most recent merge/upstream.

Below is the error that shows when running $ heroku run rake db:migrate once it gets this migration. All of the migrations before ran without any issues.

``` bash
==  RenameConversationLocked: migrating =======================================
-- rename_column(:conversations, :locked, :closed)
   -> 0.0018s
-- rename_index(:conversations, :locked, :closed)
rake aborted!
An error has occurred, this and all later migrations canceled:

PG::Error: ERROR:  relation "locked" does not exist
: ALTER INDEX "locked" RENAME TO "closed"

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Here is the full trace:

``` bash
[conclave(master)]$ heroku run rake db:migrate --trace
Running `rake db:migrate --trace` attached to terminal... up, run.1
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/Rakefile:7)
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/Rakefile:7)
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
==  RenameConversationLocked: migrating =======================================
-- rename_column(:conversations, :locked, :closed)
   -> 0.0019s
-- rename_index(:conversations, :locked, :closed)
rake aborted!
An error has occurred, this and all later migrations canceled:

PG::Error: ERROR:  relation "locked" does not exist
: ALTER INDEX "locked" RENAME TO "closed"
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:654:in `async_exec'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:654:in `block in execute'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:653:in `execute'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:1069:in `rename_index'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:466:in `block in method_missing'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:438:in `block in say_with_time'
/usr/local/lib/ruby/1.9.1/benchmark.rb:295:in `measure'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:438:in `say_with_time'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:458:in `method_missing'
/app/db/migrate/20121019161722_rename_conversation_locked.rb:4:in `up'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/usr/local/lib/ruby/1.9.1/benchmark.rb:295:in `measure'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:410:in `block in migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:123:in `with_connection'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:389:in `migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:528:in `migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:775:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/transactions.rb:208:in `transaction'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:775:in `ddl_transaction'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:719:in `block in migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:700:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:700:in `migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:570:in `up'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/migration.rb:551:in `migrate'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/railties/databases.rake:153:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/app/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/1.9.1/bin/rake:19:in `load'
/app/vendor/bundle/ruby/1.9.1/bin/rake:19:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by cashby** [comment]
Maybe we need to rollback the last two migrations and then edit AddStickyAndLockedToConversation changing locked to closed.

If we do this, will the migration run again next time or will my system know it already ran that migration once and skip it?  I guess I can always reset the database and build from the schema.rb.  However, this won't work in the long run since it destroys all of the existing data.

It seems that isn't something we would typically do so if there is another solution, I definitely want to learn about it.

**Comment by skord** [comment]
The fix got lost in the other ticket, but basically when the column ceases to exist, so does the index, so there was no index to rename. Changed the migration to reflect that and the index is created on the up and down now.
